/// <reference types="cypress"/>

import { faker } from '@faker-js/faker'
import { loginSucesso } from '../support/pages/login_page'
import { acessaCarrinho, acessaCheckout, checkSaveInfo, clicaSave, confirmaDados, confirmaErroDados, confirmaPagamento, erroCep, erroCidade, erroCmpany, erroEmail, erroEndereco, erroNome, erroObservacoes, erroPais, erroSobrenome, fechaPopup, preencheCep, preencheCidade, preencheCompany, preencheEmail, preencheEndereco, preencheNome, preencheObservacoes, preenchePais, preencheSobrenome, selecionaPagamento, verificaErro, verificaPageCheckout, verificaSuccess } from '../support/pages/checkout_page'

describe('Carrinho e Checkout', () => {
    beforeEach(() => {
        loginSucesso(faker.internet.email(), faker.internet.password()) 
        fechaPopup()
        acessaCarrinho()
        acessaCheckout()
        verificaPageCheckout()
    })
    it('Sucesso', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        confirmaDados()
        selecionaPagamento()
        confirmaPagamento()
        verificaSuccess()
    })
    it('Nome em Branco', () => {
        //preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroNome()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Sobrenome em Branco', () => {
        preencheNome(faker.person.firstName())
        //preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroSobrenome()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Company em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        //preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroCmpany()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Email em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        //preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroEmail()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('País em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        //preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroPais()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Cidade em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        //preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroCidade()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('CEP em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        //preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroCep()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Endereço em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        //preencheEndereco(faker.location.streetAddress())
        preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroEndereco()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
    it('Observações em Branco', () => {
        preencheNome(faker.person.firstName())
        preencheSobrenome(faker.person.lastName())
        preencheCompany(faker.company.name())
        preencheEmail(faker.internet.email())
        preenchePais(2)
        preencheCidade(2)
        preencheCep(faker.location.zipCode())
        preencheEndereco(faker.location.streetAddress())
        //preencheObservacoes(faker.lorem.sentence())
        checkSaveInfo()
        clicaSave()
        erroObservacoes()
        confirmaErroDados()
        selecionaPagamento()
        confirmaPagamento()
    })
})